CREATE TABLE IF NOT EXISTS Users (
  Id SERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Email TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL,
  Logged BOOLEAN DEFAULT FALSE,
  Role TEXT DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS Pitches (
  Id SERIAL PRIMARY KEY,
  Name TEXT,
  City TEXT,
  State TEXT,
  Type TEXT,
  Reserved BOOLEAN DEFAULT FALSE,
  Latitude FLOAT,
  Longitude FLOAT
  Access TEXT DEFAULT 'public';
);

CREATE TABLE IF NOT EXISTS Favorites (
  IdUser INTEGER,
  IdPitch INTEGER,
  PRIMARY KEY (IdUser, IdPitch),
  FOREIGN KEY (IdUser) REFERENCES Users(Id) ON DELETE CASCADE,
  FOREIGN KEY (IdPitch) REFERENCES Pitches(Id) ON DELETE CASCADE
);